-- Loads initial data

COPY crime_reports (
    "INCIDENT_NUMBER", "INCIDENT_TIME", "OFFENSE_NUMBER", "OFFENSE_CODE",
    "OFFENSE_CODE_DESC", "OFFENSE_RESTRICTED_INDICATOR",
    "ATTEMPTED_CRIME_FLG_DESC", "INCIDENT_BUILDING_NUMBER",
    "INCIDENT_BUILDING_SUFFIX", "INCIDENT_STREET_DIRECTION",
    "INCIDENT_STREET_NAME", "INCIDENT_STREET_NOMENCLATURE",
    "INCIDENT_BLDG_EXTENDED_TYPE", "INCIDENT_BLDG_EXTENDED_NUMBER",
    "INCIDENT_CITY", "INCIDENT_STATE", "INCIDENT_ZIP_CODE",
    "CIVIC_ASSOCIATION", "CIVIC_NAME", "COUNCIL_DISTRICT", "NEIGHBORHOOD",
    "NEIGHBORHOOD_NAME", "POLICE_PRECINCT", "POLICE_SECTOR", "DISPATCH_ZONE",
    "SUSPECTED_USED_CODE_DESC", "LOCATION_CODE_DESC", "WEAPON_CODE_DESC",
    "ENTRY_CODE_DESC", "ACTIVITY_CODE_DESC", "SECURITY_CODE_DESC",
    "EXCEPT_CLEARANCE_CODE_DESC", "DISPOSITION_CODE_DESC", "ARRESTEE_SEQ_NO",
    "ARRESTEE_BUSINESS_NAME", "ARRESTEE_FIRST_NAME", "ARRESTEE_MIDDLE_NAME",
    "ARRESTEE_LAST_NAME", "ARRESTEE_AGE_EXACT", "ARRESTEE_AGE_LOW",
    "ARRESTEE_AGE_HIGH", "ARRESTEE_BODY_BUILD_CODE_DESC",
    "ARRESTEE_RACE_CODE_DESC", "ARRESTEE_OCCUPATION",
    "ARRESTEE_RESIDENCE_CODE", "ARRESTEE_HOME_BUILDING_NO",
    "ARRESTEE_HOME_BUILDING_SUFFIX", "ARRESTEE_HOME_STREET_DIR",
    "ARRESTEE_HOME_STREET_NAME", "ARRESTEE_HOME_EXTENDED_TYPE",
    "ARRESTEE_HOME_EXTENDED_NO", "ARRESTEE_HOME_CITY", "ARRESTEE_HOME_STATE",
    "ARRESTEE_HOME_ZIP", "VEHICLE_ID", "VEHICLE_STATUS_CODE",
    "VEHICLE_STATUS_DESC", "VEHICLE_MAKE_DESC", "VEHICLE_MODEL_CODE",
    "VEHICLE_COLOR_DESC_1", "VEHICLE_COLOR_DESC_2", "VEHICLE_STOLEN_VALUE",
    "VEHICLE_RECOVERY_VALUE", "VEHICLE_RECOVERY_DATE",
    "VEHICLE_RECOVERY_BUILDING_NO", "VEHICLE_RECOVERY_STREET_DIR",
    "VEHICLE_RECOVERY_STREET_NAME", "VEHICLE_RECOVERY_CITY",
    "VEHICLE_RECOVERY_STATE", "VEHICLE_RECOVERY_ZIP"
--) FROM 'csv/crime-carytown-20130101-20131218.csv' WITH DELIMITER ',' CSV HEADER;
) FROM STDIN WITH (FORMAT csv, HEADER true);
